# Generated by Django 4.1.1 on 2022-09-22 04:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('bike_category', models.CharField(max_length=25)),
                ('country', models.CharField(blank=True, max_length=25)),
                ('bike_image', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=15)),
                ('size_rin', models.CharField(blank=True, max_length=3)),
                ('size_frame', models.CharField(blank=True, max_length=3)),
                ('brake_system', models.CharField(max_length=25)),
                ('year', models.DateField(blank=True, null=True)),
                ('bike_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.SmallIntegerField(default=1)),
                ('created_at', models.DateField(default=datetime.date.today, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('first_surname', models.CharField(max_length=50)),
                ('second_surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('departament', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_cust_order', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateField()),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='biciapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad', models.SmallIntegerField(default=1)),
                ('customer_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biciapp.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biciapp.bike')),
            ],
        ),
    ]
