# Generated by Django 4.1.1 on 2022-09-24 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biciapp', '0002_customers_groups_customers_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id_cust_order',
            new_name='id_order',
        ),
        migrations.AddField(
            model_name='order',
            name='cantidad',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='biciapp.bike'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
