# Generated by Django 4.1.1 on 2022-09-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biciapp', '0003_rename_id_cust_order_order_id_order_order_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
