# Generated by Django 4.1.1 on 2022-09-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biciapp', '0004_alter_order_price_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
